plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

def packageJson = new groovy.json.JsonSlurper().parse(file("../package.json"))

group = 'expo.modules.musiclibrary'
version = packageJson.version.toString()

android {
  namespace "expo.modules.musiclibrary"
  defaultConfig {
    versionCode 1
    versionName project.version.toString()
  }
  lint {
    abortOnError false
  }
}
