require File.join(
  File.dirname(`node --print "require.resolve('expo/package.json')"`) ,
  "scripts/autolinking"
)
require File.join(
  File.dirname(`node --print "require.resolve('react-native/package.json')"`) ,
  "scripts/react_native_pods"
)

platform :ios, ENV['DEPLOYMENT_TARGET'] || '15.1'
install! 'cocoapods', deterministic_uuids: false

prepare_react_native_project!

target 'example' do
  use_expo_modules!

  # **Just** call use_native_modules! with NO arguments
  config = use_native_modules!

  # if you need frameworks, explicitly set static linkage:
  # use_frameworks! :linkage => :static

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: (ENV['EXPO_JS_ENGINE'] != 'jsc'),
    app_path: "#{Pod::Config.instance.installation_root}/..",
    privacy_file_aggregation_enabled: true
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    installer.pods_project.targets.each do |t|
      # disable CODE_SIGNING for bundles
      t.build_configurations.each do |c|
        c.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
